name: Reusable Case Handler

on:
  workflow_call:
    inputs:
      CERT_TYPE:
        required: true
        type: string

jobs:
  Testing_certs:
    runs-on: ubuntu-latest
      
      - name: Copy cert files to ssl_certs
        run: |
          case "${{ inputs.CERT_TYPE }}" in
            tls)
              echo "This is case tls"
              # Replace with your actual commands for handling tls type
              ;;
            server)
              echo "This is case server"
              # Replace with your actual commands for handling server type
              ;;
            fullchain)
              echo "This is case Fullchain"
              # Replace with your actual commands for handling fullchain type
              ;;
            *)
              echo "Unsupported CERT_TYPE: ${{ inputs.CERT_TYPE }}"
              exit 1
              ;;
          esac
