name: Reusable Case Handler

on:
  workflow_call:
    inputs:
      CERT_TYPE:
        required: true
        type: string

jobs:
  Testing_certs:
    runs-on: ubuntu-latest
    steps:
      - name: Validate CERT_TYPE input
        run: |-
          if [[ "${{ inputs.CERT_TYPE }}" != "tls" && "${{ inputs.CERT_TYPE }}" != "server" && "${{ inputs.CERT_TYPE }}" != "fullchain" ]]; then
            echo "Unsupported CERT_TYPE: ${{ inputs.CERT_TYPE }}"
            exit 1
          fi
          
      - name: Copy cert files to ssl_certs
        run: |
          case "${{ inputs.CERT_TYPE }}" in
            tls)
              echo "This is case tls"
              # Your commands for handling tls type
              ;;
            server)
              echo "This is case server"
              # Your commands for handling server type
              ;;
            fullchain)
              echo "This is case Fullchain"
              # Your commands for handling fullchain type
              ;;
            *)
              echo "Unsupported CERT_TYPE: ${{ inputs.CERT_TYPE }}"
              exit 1
              ;;
          esac
