name: Reusable Case Handler

on:
  workflow_call:
    inputs:
      CERT_TYPE:
        required: true
        type: string

jobs:
  Deploy_Certs_To_Infrastructure:
    runs-on: ubuntu-latest 
    steps:
             
      - name: Prepare certs directory
        run: |-
          rm -rf ssl_certs/* && mkdir -p ssl_certs
          
      - name: Copy cert files to ssl_certs
        run: |-
          case "${{ inputs.CERT_TYPE }}" in
            tls)
              cp -prf fullchain.pem ssl_certs/tls.crt
              cp -rpf privkey.pem ssl_certs/tls.key
              echo "This is cert tls"
              ;;
            server)
              cp -prf fullchain.pem ssl_certs/server.crt
              cp -rpf privkey.pem ssl_certs/server.key
              echo "This is cert server"
              ;;
            fullchain)
              cp -prf fullchain.pem ssl_certs/fullchain.pem
              cp -rpf privkey.pem ssl_certs/privkey.pem
              echo "This is cert fullcahin"
              ;;
          esac
          
# jobs:
#   Testing_certs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Copy cert files to ssl_certs
#         run: |
#           case "${{ inputs.CERT_TYPE }}" in
#             tls)
#               echo "This is case tls"
#               # Replace with your actual commands for handling tls type
#               ;;
#             server)
#               echo "This is case server"
#               # Replace with your actual commands for handling server type
#               ;;
#             fullchain)
#               echo "This is case Fullchain"
#               # Replace with your actual commands for handling fullchain type
#               ;;
#             *)
#               echo "Unsupported CERT_TYPE: ${{ inputs.CERT_TYPE }}"
#               exit 1
#               ;;
#           esac
