name: Send Telegram Messages

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Set up SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     host: ${{ secrets.GCP_VM_HOST1 }}
      #     username: ${{ secrets.GCP_VM_USERNAME }}
      #     key: ${{ secrets.GCP_VM_PRIVATE_KEY }}

      - name: Copy files to GCP VM (GITHUB -- PYTHON)
        uses: appleboy/scp-action@master 
        with:
          host: ${{ secrets.GCP_VM_HOST1 }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          port: 22
          source: "."  
          target: "/var/www/html/telegram_automation" # Target directory on GCP VM

      - name: Install Dependencies
        run: python -m pip install telebot 

      - name: Debug Secrets
        run: |
          echo "TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}"
          echo "TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}"

      - name: Execute Python Script on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST1 }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          script: |
            cd /var/www/html/telegram_automation
            python3 send_telegram_message.py   



          
# name: Send Telegram Messages
# on:
#   push:
#     branches: [ telegram_automation ]

#   # schedule:
#   #   - cron: "0 0 */3 * *"  # Runs every 3 Days 

# jobs:
#   send-messages:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Install Dependencies
#         run: |
#           # python -m pip install telebot
#           pip install -r requirements.txt
          
#       # - name: Install dependencies
#       #   run: pip install python-telegram-bot

#       - name: Debug Secrets
#         run: |
#           echo "TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}"
#           echo "TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}"

      # - name: Run Python script
      #   run: python send_telegram_message.py  # Replace with your script location
      #   env:  # Set environment variables from secrets
      #     TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #     CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID}}












# name: Share Google Photos Album to Telegram

# on:
#   # push:
#   #   branches:
#   #     - main
#   workflow_dispatch:     # Allow manual triggering

# jobs:
#   send_telegram_message:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9'

#       - name: Install Dependencies
#         run:  python -m pip install telebot
    
#       - name: Debug Secrets
#         run: |
#           echo "TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}"
#           echo "TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}"

#       # - name: Install Telegram Action
#       #   uses: appleboy/telegram-action@master
#       #   with:
#       #     token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#       #     to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
#       #     message: "New push to ${{ github.repository }} repository!"

#       - name: Authenticate with Telegram And Send Message 
#         run: |
#           python - <<EOF
#           import telebot
#           bot_token = '6384770295:AAH_FlqDRXL49GM8eR5yH_WJ-K24Dsm5B4g'
#           channel_id = '-1001715673902'
#           message = 'Working on Binge+ to make it better '
#           bot = telebot.TeleBot(bot_token)
#           bot.send_message(channel_id, message)
#           print('Message sent successfully!')
          
#           EOF

     
